apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer  # or "NodePort" if using Minikube/kind
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
